export enum NotificationType {
  ALERT_TRIGGERED = 'ALERT_TRIGGERED',
  ORDER_FILLED = 'ORDER_FILLED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_REJECTED = 'ORDER_REJECTED',
  OPTION_EXPIRED = 'OPTION_EXPIRED',
  OPTION_EXERCISED = 'OPTION_EXERCISED',
  OPTION_ASSIGNED = 'OPTION_ASSIGNED',
  DIVIDEND_RECEIVED = 'DIVIDEND_RECEIVED',
  SYSTEM = 'SYSTEM',
}
